import { useState, useMemo } from 'react';
import {
  Box, Paper, Typography, Table, TableBody, TableCell, TableContainer,
  TableHead, TableRow, Chip, Stack, Dialog, DialogTitle, DialogContent,
  DialogActions, Button, Divider, TextField, InputAdornment, Alert,
  Card, CardContent, Grid
} from '@mui/material';
import { Receipt, Search, Image, Print as PrintIcon, Person } from '@mui/icons-material';
import { useApp } from '../../contexts/AppContext';

export default function HandoverReceipts() {
  const { handoverReceipts, pos } = useApp();
  const [selectedReceipt, setSelectedReceipt] = useState(null);
  const [search, setSearch] = useState('');

  const filteredReceipts = useMemo(() => {
    if (!search) return handoverReceipts;
    const s = search.toLowerCase();
    return handoverReceipts.filter(r =>
      r.karigar?.toLowerCase().includes(s) ||
      r.issuedBy?.toLowerCase().includes(s) ||
      r.pos?.some(p =>
        p.ordNo?.toLowerCase().includes(s) ||
        p.styleNo?.toLowerCase().includes(s) ||
        p.buyerName?.toLowerCase().includes(s)
      )
    );
  }, [handoverReceipts, search]);

  // Get current status of POs in a receipt
  const getPOCurrentStatus = (poId) => {
    const po = pos.find(p => p.id === poId);
    return po?.poStatus || 'UNKNOWN';
  };

  const handlePrintReceipt = (receipt) => {
    const printWindow = window.open('', '_blank');
    const posTable = receipt.pos.map(p =>
      `<tr>
        <td style="border:1px solid #ddd;padding:8px;">${p.ordNo}</td>
        <td style="border:1px solid #ddd;padding:8px;">${p.styleNo}</td>
        <td style="border:1px solid #ddd;padding:8px;">${p.buyerName}</td>
        <td style="border:1px solid #ddd;padding:8px;">${p.prodQty}</td>
        <td style="border:1px solid #ddd;padding:8px;">${p.ordDt}</td>
      </tr>`
    ).join('');

    printWindow.document.write(`
      <html>
        <head><title>Handover Receipt - ${receipt.karigar}</title></head>
        <body style="font-family:Arial,sans-serif;padding:20px;">
          <h2 style="text-align:center;">HANDOVER RECEIPT</h2>
          <hr/>
          <p><strong>Karigar:</strong> ${receipt.karigar}</p>
          <p><strong>Issued By:</strong> ${receipt.issuedBy}</p>
          <p><strong>Date & Time:</strong> ${new Date(receipt.issuedAt).toLocaleString()}</p>
          <p><strong>Total POs:</strong> ${receipt.poCount} | <strong>Total Qty:</strong> ${receipt.totalQty}</p>
          <hr/>
          <table style="width:100%;border-collapse:collapse;margin-top:10px;">
            <thead>
              <tr style="background:#f5f5f5;">
                <th style="border:1px solid #ddd;padding:8px;">Ord No</th>
                <th style="border:1px solid #ddd;padding:8px;">Style No</th>
                <th style="border:1px solid #ddd;padding:8px;">Buyer</th>
                <th style="border:1px solid #ddd;padding:8px;">Qty</th>
                <th style="border:1px solid #ddd;padding:8px;">Date</th>
              </tr>
            </thead>
            <tbody>${posTable}</tbody>
          </table>
          <div style="margin-top:30px;">
            <p><strong>Karigar Signature:</strong></p>
            <img src="${receipt.signature}" style="max-width:300px;border:1px solid #ddd;padding:5px;" />
          </div>
          <hr style="margin-top:30px;"/>
          <p style="text-align:center;color:#666;font-size:12px;">
            Receipt ID: ${receipt.id} | Generated by PO Print Management System
          </p>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <Box>
      <Typography variant="h5" fontWeight={700} gutterBottom>
        <Receipt sx={{ verticalAlign: 'middle', mr: 1 }} />
        Handover Receipts
      </Typography>
      <Typography color="text.secondary" gutterBottom>
        View all past handover records with PO details and digital signatures
      </Typography>

      {/* Search */}
      <Paper sx={{ p: 2, mb: 3 }}>
        <TextField
          fullWidth
          size="small"
          placeholder="Search by karigar name, PO number, style, buyer..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          InputProps={{
            startAdornment: <InputAdornment position="start"><Search /></InputAdornment>
          }}
        />
      </Paper>

      {/* Summary Cards */}
      <Grid container spacing={2} sx={{ mb: 3 }}>
        <Grid item xs={6} sm={3}>
          <Card>
            <CardContent sx={{ textAlign: 'center', py: 1.5 }}>
              <Typography variant="h4" fontWeight={700} color="primary.main">
                {handoverReceipts.length}
              </Typography>
              <Typography variant="caption" color="text.secondary">Total Handovers</Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={6} sm={3}>
          <Card>
            <CardContent sx={{ textAlign: 'center', py: 1.5 }}>
              <Typography variant="h4" fontWeight={700} color="secondary.main">
                {handoverReceipts.reduce((sum, r) => sum + r.poCount, 0)}
              </Typography>
              <Typography variant="caption" color="text.secondary">Total POs Issued</Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={6} sm={3}>
          <Card>
            <CardContent sx={{ textAlign: 'center', py: 1.5 }}>
              <Typography variant="h4" fontWeight={700} color="info.main">
                {handoverReceipts.reduce((sum, r) => sum + r.totalQty, 0)}
              </Typography>
              <Typography variant="caption" color="text.secondary">Total Quantity</Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={6} sm={3}>
          <Card>
            <CardContent sx={{ textAlign: 'center', py: 1.5 }}>
              <Typography variant="h4" fontWeight={700} color="success.main">
                {[...new Set(handoverReceipts.map(r => r.karigar))].length}
              </Typography>
              <Typography variant="caption" color="text.secondary">Karigars</Typography>
            </CardContent>
          </Card>
        </Grid>
      </Grid>

      {/* Receipts List */}
      {filteredReceipts.length === 0 ? (
        <Alert severity="info">
          {handoverReceipts.length === 0
            ? 'No handover receipts yet. Issue POs to karigars to create receipts.'
            : 'No receipts match your search.'}
        </Alert>
      ) : (
        <TableContainer component={Paper}>
          <Table>
            <TableHead>
              <TableRow>
                <TableCell>Receipt ID</TableCell>
                <TableCell>Karigar (Factory)</TableCell>
                <TableCell>PO Count</TableCell>
                <TableCell>Total Qty</TableCell>
                <TableCell>Issued By</TableCell>
                <TableCell>Date & Time</TableCell>
                <TableCell>Signature</TableCell>
                <TableCell>Action</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {filteredReceipts.map(receipt => (
                <TableRow key={receipt.id} hover sx={{ cursor: 'pointer' }} onClick={() => setSelectedReceipt(receipt)}>
                  <TableCell>
                    <Typography variant="body2" fontFamily="monospace" fontSize="0.75rem">
                      {receipt.id}
                    </Typography>
                  </TableCell>
                  <TableCell>
                    <Stack direction="row" spacing={1} alignItems="center">
                      <Person fontSize="small" color="action" />
                      <Typography fontWeight={600}>{receipt.karigar}</Typography>
                    </Stack>
                  </TableCell>
                  <TableCell>
                    <Chip label={receipt.poCount} size="small" color="primary" />
                  </TableCell>
                  <TableCell>{receipt.totalQty}</TableCell>
                  <TableCell>{receipt.issuedBy}</TableCell>
                  <TableCell>{new Date(receipt.issuedAt).toLocaleString()}</TableCell>
                  <TableCell>
                    {receipt.signature ? (
                      <Box
                        component="img"
                        src={receipt.signature}
                        sx={{ width: 80, height: 40, border: '1px solid', borderColor: 'divider', borderRadius: 1 }}
                      />
                    ) : (
                      <Chip label="No Signature" size="small" color="default" />
                    )}
                  </TableCell>
                  <TableCell>
                    <Button
                      size="small"
                      variant="outlined"
                      startIcon={<PrintIcon />}
                      onClick={(e) => { e.stopPropagation(); handlePrintReceipt(receipt); }}
                    >
                      Print
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      )}

      {/* Receipt Detail Dialog */}
      <Dialog open={!!selectedReceipt} onClose={() => setSelectedReceipt(null)} maxWidth="md" fullWidth>
        {selectedReceipt && (
          <>
            <DialogTitle>
              <Stack direction="row" justifyContent="space-between" alignItems="center">
                <Typography variant="h6" fontWeight={700}>
                  <Receipt sx={{ verticalAlign: 'middle', mr: 1 }} />
                  Handover Receipt
                </Typography>
                <Chip label={selectedReceipt.id} size="small" variant="outlined" />
              </Stack>
            </DialogTitle>
            <DialogContent>
              {/* Receipt Info */}
              <Paper sx={{ p: 2, mb: 3, bgcolor: 'action.hover' }}>
                <Grid container spacing={2}>
                  <Grid item xs={6} sm={3}>
                    <Typography variant="caption" color="text.secondary">Karigar</Typography>
                    <Typography fontWeight={700}>{selectedReceipt.karigar}</Typography>
                  </Grid>
                  <Grid item xs={6} sm={3}>
                    <Typography variant="caption" color="text.secondary">Issued By</Typography>
                    <Typography fontWeight={600}>{selectedReceipt.issuedBy}</Typography>
                  </Grid>
                  <Grid item xs={6} sm={3}>
                    <Typography variant="caption" color="text.secondary">Date & Time</Typography>
                    <Typography>{new Date(selectedReceipt.issuedAt).toLocaleString()}</Typography>
                  </Grid>
                  <Grid item xs={6} sm={3}>
                    <Typography variant="caption" color="text.secondary">Summary</Typography>
                    <Typography>
                      <strong>{selectedReceipt.poCount}</strong> POs |{' '}
                      <strong>{selectedReceipt.totalQty}</strong> Qty
                    </Typography>
                  </Grid>
                </Grid>
              </Paper>

              {/* PO Details Table */}
              <Typography variant="subtitle1" fontWeight={600} gutterBottom>
                PO Details
              </Typography>
              <TableContainer sx={{ mb: 3 }}>
                <Table size="small">
                  <TableHead>
                    <TableRow>
                      <TableCell>#</TableCell>
                      <TableCell>Ord No</TableCell>
                      <TableCell>Style No</TableCell>
                      <TableCell>EO No</TableCell>
                      <TableCell>Buyer</TableCell>
                      <TableCell>Qty</TableCell>
                      <TableCell>Order Date</TableCell>
                      <TableCell>Current Status</TableCell>
                    </TableRow>
                  </TableHead>
                  <TableBody>
                    {selectedReceipt.pos.map((po, idx) => (
                      <TableRow key={po.id}>
                        <TableCell>{idx + 1}</TableCell>
                        <TableCell>{po.ordNo}</TableCell>
                        <TableCell sx={{ maxWidth: 180, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                          {po.styleNo}
                        </TableCell>
                        <TableCell>{po.eoNo}</TableCell>
                        <TableCell>{po.buyerName}</TableCell>
                        <TableCell>{po.prodQty}</TableCell>
                        <TableCell>{po.ordDt}</TableCell>
                        <TableCell>
                          <Chip
                            label={getPOCurrentStatus(po.id)}
                            size="small"
                            color={
                              getPOCurrentStatus(po.id) === 'COMPLETED' ? 'success' :
                              getPOCurrentStatus(po.id) === 'ISSUED' ? 'secondary' : 'default'
                            }
                          />
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </TableContainer>

              {/* Digital Signature */}
              <Divider sx={{ mb: 2 }} />
              <Typography variant="subtitle1" fontWeight={600} gutterBottom>
                Digital Signature
              </Typography>
              {selectedReceipt.signature ? (
                <Box
                  sx={{
                    border: '2px solid',
                    borderColor: 'divider',
                    borderRadius: 2,
                    p: 2,
                    textAlign: 'center',
                    bgcolor: 'white',
                    maxWidth: 400,
                  }}
                >
                  <img
                    src={selectedReceipt.signature}
                    alt="Karigar Signature"
                    style={{ maxWidth: '100%', height: 'auto' }}
                  />
                  <Typography variant="caption" display="block" color="text.secondary" sx={{ mt: 1 }}>
                    Signed by: {selectedReceipt.karigar} | {new Date(selectedReceipt.issuedAt).toLocaleString()}
                  </Typography>
                </Box>
              ) : (
                <Alert severity="warning">No digital signature was captured for this handover.</Alert>
              )}
            </DialogContent>
            <DialogActions>
              <Button onClick={() => setSelectedReceipt(null)}>Close</Button>
              <Button
                variant="contained"
                startIcon={<PrintIcon />}
                onClick={() => handlePrintReceipt(selectedReceipt)}
              >
                Print Receipt
              </Button>
            </DialogActions>
          </>
        )}
      </Dialog>
    </Box>
  );
}
